In [31]:
import numpy as np

In [32]:
np.__version__

'2.3.1'

In [33]:
# list , array
lst = [1,2,3,4,5,6,6,]
arr = np.array(lst)

In [34]:
arr

array([1, 2, 3, 4, 5, 6, 6])

In [35]:
arr =np.array([2,3,4,5,6,])


In [36]:
arr

array([2, 3, 4, 5, 6])

In [37]:
lst = [1,3,4,5,5]
print("type of list ", type(lst))
arr =np.array(lst)
print(arr)
print("types of array",type(arr))

type of list  <class 'list'>
[1 3 4 5 5]
types of array <class 'numpy.ndarray'>


In [38]:
arr =np.array(list(range(1,23)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [39]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.ones((100))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
np.linspace(0,10,5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
# 1d arry convert into 2d array
arr =np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [46]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [48]:
arr =np.random.randint(1,5,9)
arr

array([1, 1, 1, 2, 2, 2, 3, 3, 4], dtype=int32)

In [49]:
arr =np.random.randint(1,5,(3,3))
arr

array([[1, 4, 3],
       [3, 3, 4],
       [4, 2, 4]], dtype=int32)

In [50]:
arr =np.random.random(10)
arr

array([0.29828005, 0.96510651, 0.12569744, 0.44207293, 0.83170902,
       0.33694361, 0.60657402, 0.20221086, 0.49926091, 0.38393553])

In [56]:
arr =np.random.random((5,10))
arr

array([[0.87577626, 0.62377586, 0.72178358, 0.68062398, 0.67996523,
        0.49397883, 0.97512855, 0.32285096, 0.75432318, 0.40400021],
       [0.65726469, 0.69390212, 0.23062645, 0.49362474, 0.71056698,
        0.30770877, 0.7023255 , 0.34862718, 0.20175547, 0.92641768],
       [0.98769145, 0.93054942, 0.62699306, 0.17207017, 0.12884117,
        0.70802416, 0.74914522, 0.94177975, 0.80504648, 0.75861919],
       [0.73255294, 0.68757906, 0.00267217, 0.26540184, 0.24009514,
        0.29342541, 0.77692477, 0.68641671, 0.8323673 , 0.1202382 ],
       [0.25824955, 0.60802822, 0.49837565, 0.43700031, 0.16416848,
        0.58348638, 0.58281996, 0.89706756, 0.49379808, 0.60342873]])

In [57]:
arr =np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [58]:
print("shape of array :-",arr.shape)
print("size of array", arr.size)
print("data type :-",arr.dtype)
print("number of dimension",arr.ndim)

shape of array :- (12, 5)
size of array 60
data type :- int64
number of dimension 2


In [59]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [60]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [61]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [62]:
arr.shape

(12, 5)

In [63]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [64]:
arr.T.shape

(5, 12)

In [65]:
arr =np.arange(10)

In [66]:
arr[0:12]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[0]=100

In [69]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [71]:
np.arange(60).reshape(12,5)
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [72]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [73]:
arr[1,3:5]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [75]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [76]:
arr[0:5,1:2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [80]:
arr =np.array(np.arange(225).reshape(5,15,3))

In [78]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [79]:
arr.ndim, arr.shape, arr.size, arr.dtype

(1, (10,), 10, dtype('int64'))

In [81]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [82]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [83]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [84]:
arr[0,2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [85]:
arr[0,2:,2]

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [86]:
arr[0,3:5]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [87]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [88]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [90]:
arr[0,1,1]

np.int64(4)

In [91]:
arr[0,1,1] = 1000

In [92]:
arr[0,1,1]

np.int64(1000)

In [93]:
np.array([1,2,3,4,5,6,])

array([1, 2, 3, 4, 5, 6])

In [95]:
arr.sort

<function ndarray.sort>

In [96]:
arr

array([[[   0,    1,    2],
        [   3, 1000,    5],
        [   6,    7,    8],
        [   9,   10,   11],
        [  12,   13,   14],
        [  15,   16,   17],
        [  18,   19,   20],
        [  21,   22,   23],
        [  24,   25,   26],
        [  27,   28,   29],
        [  30,   31,   32],
        [  33,   34,   35],
        [  36,   37,   38],
        [  39,   40,   41],
        [  42,   43,   44]],

       [[  45,   46,   47],
        [  48,   49,   50],
        [  51,   52,   53],
        [  54,   55,   56],
        [  57,   58,   59],
        [  60,   61,   62],
        [  63,   64,   65],
        [  66,   67,   68],
        [  69,   70,   71],
        [  72,   73,   74],
        [  75,   76,   77],
        [  78,   79,   80],
        [  81,   82,   83],
        [  84,   85,   86],
        [  87,   88,   89]],

       [[  90,   91,   92],
        [  93,   94,   95],
        [  96,   97,   98],
        [  99,  100,  101],
        [ 102,  103,  104],
        [ 105,  

In [97]:
arr+2

array([[[   2,    3,    4],
        [   5, 1002,    7],
        [   8,    9,   10],
        [  11,   12,   13],
        [  14,   15,   16],
        [  17,   18,   19],
        [  20,   21,   22],
        [  23,   24,   25],
        [  26,   27,   28],
        [  29,   30,   31],
        [  32,   33,   34],
        [  35,   36,   37],
        [  38,   39,   40],
        [  41,   42,   43],
        [  44,   45,   46]],

       [[  47,   48,   49],
        [  50,   51,   52],
        [  53,   54,   55],
        [  56,   57,   58],
        [  59,   60,   61],
        [  62,   63,   64],
        [  65,   66,   67],
        [  68,   69,   70],
        [  71,   72,   73],
        [  74,   75,   76],
        [  77,   78,   79],
        [  80,   81,   82],
        [  83,   84,   85],
        [  86,   87,   88],
        [  89,   90,   91]],

       [[  92,   93,   94],
        [  95,   96,   97],
        [  98,   99,  100],
        [ 101,  102,  103],
        [ 104,  105,  106],
        [ 107,  

In [99]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([1,6,3,5])

In [ ]:
arr1-arr2
# arr1+arr2
# arr1*arr2

array([ 0, -4,  0,  0])